# Generated by Django 5.0.7 on 2024-07-18 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
